installCRDs: true

replicaCount: 1

serviceAccount:
  create: true
  name: external-secrets

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 128Mi