apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-stores
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/mmrajput/kubernetes-homelab
    targetRevision: 1cabf3d
    path: platform/security/external-secrets/stores/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: databases

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false