apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-external-secret
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: test-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: platform/test
        property: username
    - secretKey: password
      remoteRef:
        key: platform/test
        property: password