replicaCount: 1

image:
  repository: ghcr.io/actions/gha-runner-scale-set-controller
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  annotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi