apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-cnpg-credentials
  namespace: databases
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: minio-cnpg-credentials
    creationPolicy: Owner
  data:
    - secretKey: access-key
      remoteRef:
        key: secret/data/minio/cnpg
        property: access-key
    - secretKey: secret-key
      remoteRef:
        key: secret/data/minio/cnpg
        property: secret-key