apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-staging
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: workloads
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://nextcloud.github.io/helm/
      chart: nextcloud
      targetRevision: 9.0.4
      helm:
        valueFiles:
          - $values/workloads/nextcloud/staging-values.yaml

    - repoURL: https://github.com/mmrajput/kubernetes-homelab
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud-staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
