apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-stores
  namespace: platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/mmrajput/kubernetes-homelab
    targetRevision: HEAD
    path: platform/external-secrets/stores/

  destination:
    server: https://kubernetes.default.svc
    namespace: databases

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false