apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak
  namespace: keycloak
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: keycloak
---
# Minimal RBAC - Keycloak only needs to read its own secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keycloak-secrets-reader
  namespace: keycloak
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
    resourceNames: ["keycloak-db-secret", "keycloak-admin-secret"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak-secrets-reader
  namespace: keycloak
subjects:
  - kind: ServiceAccount
    name: keycloak
    namespace: keycloak
roleRef:
  kind: Role
  name: keycloak-secrets-reader
  apiGroup: rbac.authorization.k8s.io