apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/component: dashboard
spec:
  project: default
  sources:
    - repoURL: https://jameswynn.github.io/helm-charts
      chart: homepage
      targetRevision: 2.1.0
      helm:
        valueFiles:
          - $values/apps/homepage/values.yaml

    - repoURL: https://github.com/mmrajput/kubernetes-homelab
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: homepage

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
