apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wikijs-staging
  namespace: argocd
  labels:
    app.kubernetes.io/name: wikijs-staging
    app.kubernetes.io/part-of: workloads
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: https://charts.js.wiki
      chart: wiki
      targetRevision: 3.0.0
      helm:
        valueFiles:
          - $values/workloads/wikijs/staging-values.yaml

    - repoURL: https://github.com/mmrajput/kubernetes-homelab
      targetRevision: 1cabf3d
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: wikijs-staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false