apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 9.3.0
      helm:
        valueFiles:
          - $values/platform/argocd/values.yaml
    
    - repoURL: https://github.com/mmrajput/kubernetes-homelab
      targetRevision: HEAD
      ref: values
  
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  
  syncPolicy:
    automated:
      prune: false      # Don't auto-delete (safety)
      selfHeal: true    # Auto-revert manual changes
    syncOptions:
      - CreateNamespace=true
